### ISSUE TITLE
To Do List Sunday Oct/18/2015

### ISSUE THREAD

**Issue by swethakan** [Gkxd/Jenga#3]
Hello everyone, 

I wanted to remind everyone that I will be out of town this weekend so I will not be able to meet until sunday. I’m sorry for the inconvenience. 

I’ve compiled a list based on the design document we received from Tom what areas of the game needs attention:

```
-reintroducing the pinch - pinch and grasp should both work and have an offset so hand is not directly over the block

-‘testing’ implement:  the tap/poke should work so users can feel out which block is steady

-Block Pull DONE  (Thanks Daniel!)

-Block release- a easy visual or audio to recognize when block is pulled out DONE (Thanks Daniel, the block now falls away at the)

-Block replacement - (Half way there, Daniel’s code requires you to press space for a block to generate on top. I assume this is a placeholder for a system to select which location to place the block on)

-Sounds  (halfway done - Thanks, Andrew. I will go in an adjust the sounds in a copy of the Leap Motion 4 scene, then we can introduce it to the final build)
```

Please let me know if you guys end up meeting without me, any progress etc. Also if anyone wants to pick up work on areas I just highlighted, let me and everyone else know.

**Comment by armthethinker** [comment]
Closing because I moved issues into their own spaces
